version: '3.1'

services:

  db:
    build:
      dockerfile: Dockerfile.db
      context: .
    restart: always
    volumes:
      - data-mysql:/var/lib/mysql
      - ./docker/sql/codepush-all.sql:/docker-entrypoint-initdb.d/codepush-all.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codepush

  redis:
    image: docker.io/library/redis:4.0.11-alpine
    volumes:
      - data-redis:/data
    ports:
      - 6379:6379

  adminer:
    image: docker.io/library/adminer
    restart: always
    ports:
      - 9090:8080

  appsync:
    build: .
    restart: always
    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      LOCAL_DOWNLOAD_URL: "http://192.168.1.23:3000/download"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_USERNAME: "codepush"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "codepush"
      STORAGE_DIR: "/data/storage"
      DATA_DIR: "/data/tmp"
      NODE_ENV: "production"
      CONFIG_FILE: "/opt/nativescript-app-sync-server/config/config.js"
      RDS_HOST: "redis"
      RDS_PORT: "6379"
      STORAGE_TYPE: "local"

volumes:
  data-storage:
  data-tmp:
  data-mysql:
  data-redis:
